name: Add Gaussian Noise and Upload Dataset

on:
  push:
    branches: [ActionTesting]


jobs:
  add-noise:
    if: github.ref == 'refs/heads/ActionTesting'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install --upgrade huggingface_hub numpy pillow tqdm opencv-python tqdm

    - name: Download dataset from Hugging Face
      run: |
        mkdir -p /tmp/data
        wget -O /tmp/data/imagewoof2.tgz https://huggingface.co/datasets/TT2002/imagewoofprivate/resolve/main/imagewoof2.tgz
        tar -xzf /tmp/data/imagewoof2.tgz -C /tmp/data

    # - name: Run noiselinux.py on dataset
    #   run: |
    #     python noiselinux.py /tmp/data/imagewoof2 /tmp/data/gauss_imagewoof

    - name: Upload noisy dataset to Hugging Face
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        python - <<EOF
        from huggingface_hub import HfApi

        api = HfApi()
        api.upload_file(
        path_or_fileobj="/tmp/data/imagewoof2/train/n02086240/ILSVRC2012_val_00000907.JPEG",
        path_in_repo="train/n02086240/ILSVRC2012_val_00000907.JPEG",
        repo_id="TT2002/gauss_imagewoof",
        repo_type="dataset",
        token="${{ env.HF_TOKEN }}"
        )
        EOF


