name: Run filecountlinux.py on dataset

on:
  push:
    branches: [ActionTesting]  # or "main" 

jobs:
  filecount:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install gdown

    - name: Download and extract dataset from Hugging Face
      run: |
        mkdir -p /tmp/data
        wget -O /tmp/data/imagewoof2.tgz https://huggingface.co/datasets/TT2002/imagewoofprivate/resolve/main/imagewoof2.tgz
        tar -xzf /tmp/data/imagewoof2.tgz -C /tmp/data


    - name: Run filecount.py
      run: |
        python filecount.py /tmp/data/imagewoof2
